FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine AS build-env
WORKDIR /App
COPY . ./
RUN dotnet restore AZServiceBusWorker.csproj
RUN dotnet publish -c Release -o out AZServiceBusWorker.csproj

FROM mcr.microsoft.com/dotnet/runtime:8.0-alpine
WORKDIR /App
COPY --from=build-env /App/out .
ENTRYPOINT ["dotnet", "AZServiceBusWorker.dll"]