FROM mcr.microsoft.com/dotnet/sdk:8.0-alpine as build
COPY . /app
WORKDIR /app
RUN dotnet publish -c Release -o /publish WeatherForecastAPI.csproj

FROM mcr.microsoft.com/dotnet/aspnet:8.0-alpine as base
COPY --from=build /publish /app
WORKDIR /app
EXPOSE 8080
ENTRYPOINT ["dotnet", "WeatherForecastAPI.dll"] 